# exemplo criando com linha de comando 
# kubectl create secret generic mysecret --from-literal=username=SnVsaW8= --from-literal=password=MTIzNDU=

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: aplicacao
type: Opaque
data:
  username: SnVsaW8=
  password: MTIzNDU=
  # Example:
  # password: {{ .Values.password | b64enc }}
