apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod3
  name: pod3
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts: #definindo o volume dentro do container
    - mountPath: /primeiro-volume
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests: 
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: # criando o volume
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi  

