
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod3
  name: ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "600"  
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests: 
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
