apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deployment
  namespace: aplicacao
spec:
  replicas: 1  # Adicionado valor para replicas
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: meu-pvc  # Alterado para 'meu-pvc'

