apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: meu-storage-class
  namespace: aplicacao
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
