apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: meu-storage
  nfs:
    path: /mnt/nfs/nginx-0 # Caminho no servidor NFS
    server: 192.168.1.12 # IP do servidor NFS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: meu-storage
  nfs:
    path: /mnt/nfs/nginx-1
    server: 192.168.1.12
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: meu-storage
  nfs:
    path: /mnt/nfs/nginx-2
    server: 192.168.1.12
