apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: meu-pvc
  name: meu-pvc  
  namespace: aplicacao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "meu-storage"   
  selector:
    matchLabels:
      storage: nfs 

