apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: meu-pvc
  name: meu-pvc  # Alterado de 'pvc' para 'meu-pvc' para coincidir com o claimName no Deployment
  namespace: aplicacao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "meu-storage"   
  selector:
    matchLabels:
      storage: nfs  # Corrigido 'nfsS' para 'nfs'

